-- =============================================================================
-- CampusStay Hostel Management System - Supabase / PostgreSQL Schema Definition
-- =============================================================================

-- Enable UUID extension if required
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Create Rooms Table
CREATE TABLE IF NOT EXISTS public.rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_number VARCHAR(20) NOT NULL UNIQUE,
    block_name VARCHAR(50) DEFAULT 'Block A',
    room_type VARCHAR(50) DEFAULT 'SHARED_DOUBLE', -- SINGLE_DELUXE, SHARED_DOUBLE, SHARED_TRIPLE
    capacity INT NOT NULL CHECK (capacity > 0),
    occupied INT NOT NULL DEFAULT 0 CHECK (occupied >= 0 AND occupied <= capacity),
    monthly_fee NUMERIC(10, 2) DEFAULT 6000.00,
    status VARCHAR(20) NOT NULL DEFAULT 'AVAILABLE' -- AVAILABLE, FULL, MAINTENANCE
);

-- 2. Create Students Table
CREATE TABLE IF NOT EXISTS public.students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    phone VARCHAR(25) NOT NULL,
    emergency_contact VARCHAR(25),
    room_id BIGINT NOT NULL REFERENCES public.rooms(id) ON DELETE RESTRICT,
    check_in_date DATE DEFAULT CURRENT_DATE,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. Create Performance Indexes
CREATE INDEX IF NOT EXISTS idx_rooms_status ON public.rooms(status);
CREATE INDEX IF NOT EXISTS idx_rooms_block ON public.rooms(block_name);
CREATE INDEX IF NOT EXISTS idx_students_room_id ON public.students(room_id);
CREATE INDEX IF NOT EXISTS idx_students_email ON public.students(email);

-- 4. Enable Row Level Security (RLS) & Policies
ALTER TABLE public.rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;

-- Allow full access for service key / public authenticated role
CREATE POLICY "Allow public read rooms" ON public.rooms FOR SELECT USING (true);
CREATE POLICY "Allow public insert update rooms" ON public.rooms FOR ALL USING (true);

CREATE POLICY "Allow public read students" ON public.students FOR SELECT USING (true);
CREATE POLICY "Allow public insert update students" ON public.students FOR ALL USING (true);
